name: Update Feed
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update_feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run parser
        run: python FeedMerger.py

      - name: Send notification
        env:
          SECRET_WEBHOOK_URL: ${{ secrets.SECRET_WEBHOOK_URL }}
          SECRET_WEBHOOK_URL2: ${{ secrets.SECRET_WEBHOOK_URL2 }}
        run: |
          python RSSparser.py $SECRET_WEBHOOK_URL $SECRET_WEBHOOK_URL2

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@github.com"
          
          git add feed.xml posted_links.txt
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "RSS Feed Update"
            git push
          fi