name: Notification

on:
  push:
    branches:
      - main

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification
        env:
          SECRET_WEBHOOK_URL: ${{ secrets.SECRET_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content":"This is a test message"}' \
          $SECRET_WEBHOOK_URL
