name: RSS Feed Update

on:
  workflow_run:
    workflows: ["Update Feed"]
    types:
      - completed

jobs:
  update_after_feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser

    - name: Run Python script
      run: python RSSparser.py

    - name: Use curl to send payload
      env:
        SECRET_WEBHOOK_URL: ${{ secrets.SECRET_WEBHOOK_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d @payload.json $SECRET_WEBHOOK_URL
